val = input("Enter a value: ")
print("You entered:", val)
print("The type of the value is:", type(val))
print("The length of the value is:", len(val))
print("The value in uppercase is:", val.upper())
print("The value in lowercase is:", val.lower())
print("The value reversed is:", val[::-1])
print("The value with spaces removed is:", val.replace(" ", ""))
print("The value with spaces replaced by underscores is:", val.replace(" ", "_"))
print("The value with the first letter capitalized is:", val.capitalize())
print("The value with the first letter of each word capitalized is:", val.title())
print("The value with the first and last characters removed is:", val[1:-1])
print("The value with the first 3 characters removed is:", val[3:])
print("The value with the last 3 characters removed is:", val[:-3]) 
print("The value with the first 3 characters replaced by 'X' is:", "X" * 3 + val[3:])
print("The value with the last 3 characters replaced by 'X' is:", val[:-3] + "X" * 3)
print("The value with all characters replaced by 'X' is:", "X" * len(val))
print("The value with all vowels replaced by 'X' is:", val.replace("a", "X").replace("e", "X").replace("i", "X").replace("o", "X").replace("u", "X").replace("A", "X").replace("E", "X").replace("I", "X").replace("O", "X").replace("U", "X"))